---

- block:
    - name: add docker repo for most recent docker builds
      yum_repository:
        name: docker
        description: Docker Repository
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: ensure python-docker-py and yum-plugin-versionlock packages are installed
      package: name={{ item }} state=latest
      loop:
        # This also automatically obsoletes and removes an old docker-python RPM if installed
        - python-docker-py
        - yum-plugin-versionlock

    - set_fact:
        package_manager_path: /bin/yum
  when: ansible_os_family == 'RedHat' and ansible_distribution != "Fedora"

- block:
    - name: add docker repo for most recent docker builds
      yum_repository:
        name: docker
        description: Docker Repository
        baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/fedora/gpg
        enabled: yes

    - name: ensure python3-docker and python3-dnf-plugin-versionlock packages are installed
      package: name={{ item }} state=latest
      loop:
        - python3-docker
        - python3-dnf-plugin-versionlock

    - set_fact:
        package_manager_path: /usr/bin/dnf
  when: ansible_os_family == 'RedHat' and ansible_distribution == "Fedora"

- name: versionlock docker-ce
  command: "{{ package_manager_path }} versionlock {{ docker_install_versionlock | join(' ') }}"
  args:
    warn: no
  ignore_errors: yes

- name: install docker
  package:
    name:
      - "docker-ce-{{ docker_version }}"
      - "docker-ce-cli-{{ docker_version }}"
      - "docker-compose-plugin-{{ docker_compose_version }}"
    state: present
  register: yum_docker

- name: versionlock docker-ce
  command: "{{ package_manager_path }} versionlock {{ docker_install_versionlock | join(' ') }}"
  args:
    warn: no

# See https://github.com/containers/container-selinux/pull/64#issuecomment-461518027
- name: ensure that SELinux labels are set correctly
  shell: /usr/sbin/restorecon -RvF $(rpm -ql containerd.io docker-ce)

- name: delete old docker-compose standalone binary
  file:
    path: /usr/local/bin/docker-compose
    state: absent
