---
# Docker changes: https://github.com/docker/docker/blob/master/CHANGELOG.md

- import_tasks: install.yml

- import_tasks: selinux.yml

- import_tasks: tls.yml

- import_tasks: swarm.yml
  when: docker_swarm
